version: '3.9'
services:
  red-app:
    image: trafficlight/red
    container_name: red-app
    networks:
      - traffic-light
    ports:
      - 4000:80

  yellow-app:
    image: trafficlight/yellow
    container_name: yellow-app
    networks:
      - traffic-light
    ports:
      - 3000:80
  green-app:
    image: trafficlight/green
    container_name: green-app
    networks:
      - traffic-light
    ports:
      - 5000:80
  proxy:
    image: nginx
    container_name: proxy
    networks:
      - traffic-light
    ports:
        - 80:80
    
    depends_on:
      - red-app
      - yellow-app
      - green-app

networks:
  traffic-light:
    driver: bridge